dist: xenial

language: node_js
node_js:
  - node

install:
  - npm install

script:
  - npm run setup || travis_terminate 1
  - npm run init || travis_terminate 1
  - npm run build || travis_terminate 1
  - npm run lint
  - npm run doc || travis_terminate 1
  - npm run check || travis_terminate 1
  - npm run test || travis_terminate 1
  - npm run example || travis_terminate 1

cache: npm
